### ISSUE TITLE
Integration with test navigator broken in latest version of Xcode

### ISSUE THREAD

**Issue by modocache** [specta/specta#85]
After merging PR #83, you may realize that Specta does not correctly report spec success/failure in the Xcode test navigator.

As of Xcode 6, each test invocation's selector is used to determine the name displayed in the test navigator. Specta uses the same instance method to run each example. As a result, all tests in the same spec had the same name, causing each example to "overwrite" each previous one in the navigator. This caused several issues, including red lines to indicate test failure in Xcode suddenly disappearing when the next example finished running.

This can be fixed by dynamically defining a new instance method for each example, then creating an invocation to execute that instance method.

You can find more details here: https://github.com/modocache/Quick/issues/1

A working implementation of dynamic method definition is here: https://github.com/modocache/Quick/blob/606d77ab12faac00386f24872e33a0347711f0ec/Quick/Core/QuickSpec.m#L33

**Comment by mmiroslav** [comment]
Any news about this issue?

**Comment by StatusReport** [comment]
This has not been solved yet, and not been solved in Quick regardless of @modocache's post. See Quick/Quick#157, Quick/Quick#219. Seems like the problem is on Apple's end, and until someone will reverse engineer Xcode it seems that the only option that works for me is to restart Xcode.

**Comment by modocache** [comment]
@StatusReport The problem this issue originally reported, that all tests show up as `spt_runExampleAtIndex:`, has been fixed. The issues you reference still exist in all frameworks that use dynamic test invocations, whether that's Specta or Quick.

I'm closing this issue to avoid confusion. Please open new issues for problems with the test navigator. Or better yet, file radars. :wink:

**Comment by esttorhe** [comment]
I'm still seeing all my tests as `spt_runExampleAtIndex:` and I'm on `Version 6.3.1 (6D1002)` of `Xcode` ¯\_(ツ)_/¯

**Comment by esttorhe** [comment]
nvm; it was a PEBCAK problem
